### ISSUE TITLE
Tugas1

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD1201#1]

**Comment by IBRAHIM354313** [comment]
Nama : Muhammad Musa Ibrahim
Nrp : 2C2230002

https://github.com/IBRAHIM354313/TugasAlpro
https://github.com/IBRAHIM354313/TugasAlpro/blob/main/Tugas%201%20PSEUDOCODE_Muhammd%20Musa%20Ibrahim.pdf

**Comment by revaanwarr** [comment]
**Reva Anwar** - **_2C2230003_**
https://github.com/revaanwarr/TugasPemrogramandasar
https://github.com/revaanwarr/TugasPemrogramandasar/tree/main

**Comment by AmeliaReginaa** [comment]
Amelia Regina P - 2C2230019
https://github.com/AmeliaReginaa/T.Pemrograman_Dasar

**Comment by KanayaDzikra** [comment]
Kanaya Dzikra 2C2230015

https://github.com/KanayaDzikra/Pemograman-dasar
https://github.com/KanayaDzikra/Pemograman-dasar/blob/main/Tugas%201%20Pseudecode.pdf

**Comment by nadinevaliaa** [comment]
Nadine Valia Azzahra - 2C2230007

https://github.com/nadinevaliaa/TugasPemrogramanDasar
https://github.com/nadinevaliaa/TugasPemrogramanDasar/blob/main/Tugas%201%20PSEUDOCODE.pdf

**Comment by ajisakti554** [comment]
Aji Sakti Saputra - 2C2230012
https://github.com/ajisakti554/Tugas-Alpro/blob/main/WhatsApp%20Image%202024-03-08%20at%2019.39.25.jpeg
https://github.com/ajisakti554/Tugas-Alpro/blob/main/WhatsApp%20Image%202024-03-08%20at%2019.39.26.jpeg

**Comment by yusufsf01** [comment]
Yusuf Sohibul Falah 2C2230013
https://github.com/yusufsf01/PemrogramanDasar/blob/main/YusufSohibulFalah_2C2230013_PemrogramanDasar.pdf

**Comment by rafaza24** [comment]
RAFID FARHAN ZAI 
![WhatsApp Image 2024-03-07 at 21 51 12_54e92171](https://github.com/sevinurafni/SD1201/assets/154486040/7a0b545a-cda3-4482-92c0-0c0189e8d41b)
![WhatsApp Image 2024-03-07 at 22 07 13_60654ec8](https://github.com/sevinurafni/SD1201/assets/154486040/3ee65023-c278-4f68-ad77-85d5775787c4)

**Comment by ApikMu** [comment]
Ahmad muwafiqul 'adli - 2C2230006
[Tugas 1 PSEUDOCODE_Ahmad Muwafiqul 'Adli.pdf](https://github.com/sevinurafni/SD1201/files/14540432/Tugas.1.PSEUDOCODE_Ahmad.Muwafiqul.Adli.pdf)

**Comment by najliaa** [comment]
Najlia Intani 2C2230010
https://github.com/najliaa/Tugas-Pemrograman-Dasar/tree/main/Tugas%201%20PD

**Comment by ryynnptr** [comment]
Riyan putra pratama 2C2230016
https://github.com/ryynnptr/pemrograman.dasar/tree/051ad1733d9709aef5ebb11e875535c4c9450cd3/Tugas%201

**Comment by ArielaSafra** [comment]
Ariela Safmi Ramdhani - 2C2230005
https://github.com/ArielaSafra/ArielaSafmi-SD1201/blob/main/Ariela%20Safmi_Pemrograman%20Dasar%20(1).pdf

**Comment by HansDarmawanS** [comment]
Farhan Darmawan S - 2C2230017

https://github.com/HansDarmawanS/TugasProgramDasar
