### ISSUE TITLE
Tugas 3

### ISSUE THREAD

**Issue by sevinurafni** [sevinurafni/SD1201#3]

**Comment by HansDarmawanS** [comment]
Kelompok 2 : 
- Farhan Darmawan (2C2230017) 
- Ariela Safmi (2C2230005) 
- Nadine Valia (2C2230007) 
- Kanaya Dzikra (2C2230015)

https://github.com/HansDarmawanS/TugasProgramDasar

**Comment by najliaa** [comment]
KELOMPOK 1
- Najlia Intani - 2C2230010
- Reva Anwar - 2C2230003
- Rafid Farhan Zai - 2C2230001
- Muhammad Musa Ibrahim - 2C2230002

https://github.com/najliaa/Tugas-Pemrograman-Dasar/blob/main/Manajemen%20Perpustakaan%20Kel%201.cpp

**Comment by ryynnptr** [comment]
KELOMPOK 4

-Budi kurnia - 2C2230018
-Fadhli jahfal aufa maulana - 2C2230008
-Riyan putra pratama - 2C2230026

https://github.com/ryynnptr/pemrograman.dasar/blob/main/Tugas%203%20Kelompok/main.cpp

**Comment by AmeliaReginaa** [comment]
Kelompok 5 
-Amelia Regina Permana - 2C2230019
- Rizwar Syaefulloh - 2C2230009
- Yusuf Sohibul Falah - 2C2230013
https://github.com/AmeliaReginaa/T.Pemrograman_Dasar/blob/main/perpus.cpp
https://github.com/AmeliaReginaa/T.Pemrograman_Dasar/blob/main/Output%20Manajemen%20Perpus%20Kel%205.pdf
